// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Models;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(FileDbContext))]
    [Migration("20200717124131_firstmigration")]
    partial class firstmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication1.Models.Languages", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Language")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Languages");
            });

            modelBuilder.Entity("WebApplication1.Models.Movie", b =>
            {
                b.Property<int>("MovieId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<int?>("LanguageId")
                    .HasColumnType("int");

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("MovieId");

                b.HasIndex("LanguageId");

                b.ToTable("Movies");
            });

            modelBuilder.Entity("WebApplication1.Models.Reviews", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<int?>("MovieId")
                    .HasColumnType("int");

                b.Property<string>("ReviewString")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("MovieId");

                b.ToTable("Reviews");
            });

            modelBuilder.Entity("WebApplication1.Models.Movie", b =>
            {
                b.HasOne("WebApplication1.Models.Languages", "Language")
                    .WithMany()
                    .HasForeignKey("LanguageId");
            });

            modelBuilder.Entity("WebApplication1.Models.Reviews", b =>
            {
                b.HasOne("WebApplication1.Models.Movie", "Movie")
                    .WithMany()
                    .HasForeignKey("MovieId");
            });
#pragma warning restore 612, 618
        }
    }
}